### ISSUE TITLE
[1.8.3] Validation required in request Builder classes such as UsersRequest , GroupRequest , MessageRequest 

### ISSUE THREAD

**Issue by yadavmangesh** [cometchat-pro/android-chat-sdk#10]
**Describe the bug**
 Null or random values can be set in the current Request Builder classes 

**To Reproduce**
Example
```
UsersRequest usersRequest=new UsersRequest.UsersRequestBuilder().setLimit(100)
                    .setUserStatus(null)
                    .setSearchKeyword("iron Man").build();
```

```
UsersRequest usersRequest=new UsersRequest.UsersRequestBuilder().setLimit(0)
                                                   .setSearchKeyword("iron Man").build();

```

**Expected behavior**
Should have given an error or warning on setting null values or other than  required 

**Actual behavior**
   returns result even after setting null values in the builder

**Enviorment/Platfrom (please complete the following information):**
 - Android API Version[Android 5.1 || API 22 ]
 - CometChat SDK Version[1.8.3]

**Logs (Error Logs)**
- Error Log
  No error log

**Comment by adityagokula2210** [comment]
Done
