### ISSUE TITLE
[1.8.8] Inconsistency in naming for action message for Scope changed

### ISSUE THREAD

**Issue by pushpsenairekar2911** [cometchat-pro/android-chat-sdk#14]
*Describe the bug**
On Android, we get "System made Joe Doe admin" text
On iOS, we get "Joe Doe's scope changed from participant to participant" text

**Expected behavior**
Action message should be the same. 

**Actual behavior**
getting different action message for the same action.

**Comment by adityagokula2210** [comment]
@pushpsenairekar2911 
Please list down the text we provide for all the action messages here and i will list down the text we use for android. @mayur-bhandari , please list down the text for action messages used in javascript SDK too. Let's compare and come to a final list and then make the changes..??

**Comment by adityagokula2210** [comment]
For android,

public static final String ACTION_GROUP_JOINED_MESSAGE = "superhero1 joined";
        public static final String ACTION_GROUP_LEFT_MESSAGE = "superhero1 left";
        public static final String ACTION_MEMBER_KICKED_MESSAGE = "superhero1 kicked superhero2";
        public static final String ACTION_MEMBER_BANNED_MESSAGE = "superhero1 banned superhero2";
        public static final String ACTION_MEMBER_UNBANNED_MESSAGE = "superhero1 unbanned superhero2";
        public static final String ACTION_MESSAGE_EDITED_MESSAGE = "Message Edited";
        public static final String ACTION_MESSAGE_DELETED_MESSAGE = "Message Deleted";
        public static final String ACTION_MEMBER_ADDED_TO_GROUP = "superhero1 added superhero2";
        public static final String ACTION_MEMBER_SCOPE_CHANGED = "superhero1 made superhero2 admin";

**Comment by pushpsenairekar2911** [comment]
For iOS,

public static let ACTION_GROUP_JOINED_MESSAGE = "superhero1 joined";

        public static let ACTION_GROUP_LEFT_MESSAGE = "superhero1 left
Comic hero's";

        public static let ACTION_MEMBER_KICKED_MESSAGE = "superhero1 kicked
superhero2 ";

        public static let ACTION_MEMBER_BANNED_MESSAGE = "superhero1 banned
superhero2";

        public static let ACTION_MEMBER_UNBANNED_MESSAGE = "superhero1
unbanned superhero2";

        public static let ACTION_MESSAGE_SCOPE_CHANGED_MESSAGE = "superhero1's
scope changed from participant to admin"

        public static let ACTION_MESSAGE_EDITED_MESSAGE = "Message is
edited.";

        public static let ACTION_MESSAGE_DELETED_MESSAGE = "Message is
deleted.";

    public static let ACTION_MESSAGE_ADDED_MESSAGE = "superhero1 added
superhero2";

Warm Regards,

Pushpsen Airekar
Associate Software Engineer

M: +918208020656 | T (India): +91 22 30551023 | T (U.S.): +1 415 287 0451

Inscripts (I) Pvt. Ltd. |  An ISO 9001:2008 Certified Company
517-518 Shrikant Chambers, V.N. Purav Marg, Chembur, Mumbai – 400 071
http://www.inscripts.com

**Comment by mayur-bhandari** [comment]
@aditya.gokula@inscripts.com
We have to make changes only in v2 or in both v1.8 and v2?

**Comment by adityagokula2210** [comment]
Resolved
