### ISSUE TITLE
[2.0.0-beta4] Override hashCode() , equals() , clone() ,toStrings() in all pojo classes of CometChat Pro SDK

### ISSUE THREAD

**Issue by yadavmangesh** [cometchat-pro/android-chat-sdk#15]
**Describe the bug**
`hashCode()` and `equals()` are not overriden in all POJO classes 

**Expected behavior**
   all objects are available for comparison using `equals()`

**Actual behavior**
   methods not available in POJOs

**Enviorment/Platfrom (please complete the following information):**
 - CometChat SDK Version[2.0.0-beta4]

**Comment by adityagokula2210** [comment]
Released in 2.0.0-beta9
