### ISSUE TITLE
[1.8.8] Audio call can be switched to Video Call

### ISSUE THREAD

**Issue by darshanbhanushali** [cometchat-pro/android-chat-sdk#17]
**Describe the bug**
Audio Call can be switch to Video call through Video call button on screen.

**Expected behavior**

  Video call button must be disabled, so Audio call cannot be switched to Video Call

**Actual behavior**

  Audio call can be switched to Video call.

**Enviorment/Platfrom (please complete the following information):**
 - CometChat SDK Version[1.8.8]

**Comment by adityagokula2210** [comment]
Fixed in 2.1.0
