### ISSUE TITLE
Voice Calling not working in WiFi Conncetion.

### ISSUE THREAD

**Issue by dilnawaz45** [cometchat-pro/android-chat-sdk#19]
Dear Sir, 

I had made voice calling an Android app but I had faced a problem
When I make a call using a WiFi connection, applications are disconnected and automatically restarted. But when I used cellular data, my app was working fine.

Please send me the solution.
Thank you

**Comment by adityagokula2210** [comment]
Hello,
We have released a new version of the Android SDK (2.1.0). This version consists of a totally new Calling module which is more optimized and allows customizations. Please upgrade to the latest version and you should not face this issue again. Please do provide us with your feedback.
Thanks
