### ISSUE TITLE
Voice calling is only working on loudspeakers

### ISSUE THREAD

**Issue by dilnawaz45** [cometchat-pro/android-chat-sdk#20]
Dear Sir, 

I had made voice calling (Only audio calling) an Android app but I had faced a problem
Voice calling is only working on loudspeakers. I want audio calling without loudspeaker

Please send me the solution.
Thank you

**Comment by darshanbhanushali** [comment]
Hi @dilnawaz45 Thank you for reporting the issue, We are working on Calling Functionality and will let you know once it is updated.

**Comment by adityagokula2210** [comment]
Hello,
We have released a new version of the Android SDK (2.1.0). This version consists of a totally new Calling module which is more optimized and allows customizations. Please upgrade to the latest version and you should be able to switch the audio output.
Thanks
