### ISSUE TITLE
[2.0.1] Audio/Video Call shows blank screen on network loss while call is running.

### ISSUE THREAD

**Issue by darshanbhanushali** [cometchat-pro/android-chat-sdk#21]
**Describe the bug**
After connectivity loss, call view freezes for something like 10 seconds, and during this time if network appears the call is reconnected, but after this 10 seconds call view entirely disappears with no callback, and you can not reconnect to call anymore. Is there any workaround or fix for this problem?

**Expected behavior**

  Call must reconnect again after connection re-established or show some error if call is terminated.

**Actual behavior**

  Calling screen shows blank black screen after connection lost while call is running.

**Enviorment/Platfrom (please complete the following information):**
 - CometChat SDK Version[ 2.0.1]

**Comment by adityagokula2210** [comment]
Fixed in 2.1.0
