### ISSUE TITLE
[2.0.1] Reasons for minSdkVersion 21

### ISSUE THREAD

**Issue by Arrefelt** [cometchat-pro/android-chat-sdk#22]
Just wondering what features of the CometChat SDK requires API 21 and if there are any plans on lowering it? 

Since our app is currently only requiring 16, it's a somewhat big jump for us to even be able to use CometChat. As of now, seems like about 10,7% of Android users are on <21 and 6.9% are on 19, so being able to lower to at least 19 would be great.

**Comment by adityagokula2210** [comment]
Hello @Arrefelt 
Unfortunately, we do not plan to reduce the minimum SDK version for the CometChat Android SDK any time in the near future. The main reason for this is that our calling component uses various webrtc related components that require the minimum SDK version to be set to 21.
We regret the inconvenience caused.

**Comment by Arrefelt** [comment]
Ok, thanks for the clarification!
