### ISSUE TITLE
Customization in calling UI 

### ISSUE THREAD

**Issue by yadavmangesh** [cometchat-pro/android-chat-sdk#27]
**Describe the issue**

Features Added and Improvement
1.  Customizable  UI.
2.  Ability to switch between multiple audio sources.
3.  Easy integration and full backward compatibility.
4.  Ability to customize the default UI.

**Comment by hilmyas** [comment]
"Ability to switch between multiple audio sources." -> how to do that?

**Comment by jitvarpatil** [comment]
@hilmyas we have added this functionality in our latest SDK `v2.1.0-beta2`. For more details on this, you can follow the documentation at the following link:

https://prodocs.cometchat.com/v2.1/docs/android-calling
