### ISSUE TITLE
 Exception cannot convert String to JSON

### ISSUE THREAD

**Issue by Salmancs43** [cometchat-pro/android-chat-sdk#29]
When the metadata is set in call object it returns a string instead of JSONObject in response. which throws the exception cannot convert String to JSON Object as SDK end.

**Comment by adityagokula2210** [comment]
Hello @Salmancs43 
We are aware of this issue and this will be resolved in our next API Release scheduled for end of this week. You can follow the below Github Issue to track the progress for this:

https://github.com/cometchat-pro/rest-api/issues/17

I will be closing this issue as we would like to have a single channel of communication. 
Thans
