### ISSUE TITLE
Mute issue with audio calls

### ISSUE THREAD

**Issue by im-ng** [cometchat-pro/android-chat-sdk#3]
Connected audio call always stay with mute state. Not able to unmute for conversation.

Dependency used:

```
implementation ('com.cometchat:pro-android-chat-sdk:1.7.+') {
        configurations {
            compile.exclude module: 'gson'
            compile.exclude module: 'okhttp'
            compile.exclude module: 'okio'
        }
    }
```

**Comment by adityagokula2210** [comment]
@ng28 
Can you please confirm if the necessary permissions are granted to the app.

`<uses-permission android:name="android.permission.CAMERA" />`
`<uses-permission android:name="android.permission.RECORD_AUDIO" />`

These are the two permissions required for audio/video calling. I dont think this problem should occur if the necessary permissions are granted. Please confirm.

Thanks!

**Comment by im-ng** [comment]
@adityagokula2210 Yep you are correct. Seems we messed with permission order in our app launch. I am able to mute/unmute with record_audio permission now. Thanks for clarification.

**Comment by adityagokula2210** [comment]
No Problem.. happy to help.
Closing the issue.

Thanks!
