### ISSUE TITLE
Entry name 'XPP3_1.1.4c_VERSION'

### ISSUE THREAD

**Issue by rsanjuan87** [cometchat-pro/android-chat-sdk#32]
Hi
I'm getting this error

`Entry name 'XPP3_1.1.4c_VERSION' collided`

versions of gradle 6.5, and android_gradle_plugin 4.0.0
here is the output of `gradlew app:dependencies`

[deps.log](https://github.com/stripe/stripe-android/files/4900297/deps.log)

```
+--- com.cometchat:pro-android-chat-sdk:2.0.3
|    +--- org.igniterealtime.smack:smack-android:4.1.0
|    |    +--- org.igniterealtime.smack:smack-resolver-minidns:4.1.0
|    |    |    +--- de.measite.minidns:minidns:[0.1,0.2) -> 0.1.7
|    |    |    +--- org.jxmpp:jxmpp-util-cache:0.4.2-beta1
|    |    |    \--- org.igniterealtime.smack:smack-core:4.1.0
|    |    |         +--- org.jxmpp:jxmpp-core:0.4.2-beta1
|    |    |         |    \--- org.jxmpp:jxmpp-util-cache:0.4.2-beta1
|    |    |         \--- xpp3:xpp3:1.1.4c

...

xpp3:xpp3:{strictly 1.1.4c} -> 1.1.4c (c)
```

about xpp3

`xpp3 defines classes that conflict with classes now provided by Android. Solutions include finding newer versions or alternative libraries that don't have the same problem (for example, for httpclient use HttpUrlConnection or okhttp instead), or repackaging the library using something like jarjar`

**Comment by rsanjuan87** [comment]
Please any help?

**Comment by adityagokula2210** [comment]
Hello @rsanjuan87 
Can you please share your app-level gradle file with me so that I can have a look at this and try to regenerate this at my end. This will help me investigate better.

Thanks

**Comment by rsanjuan87** [comment]
Hello @adityagokula2210 
here is
[app_build.gradle.zip](https://github.com/cometchat-pro/android-chat-sdk/files/4922511/app_build.gradle.zip)
thanks

**Comment by adityagokula2210** [comment]
Hello @rsanjuan87 ,
I am checking this. Please allow us some time.

Thanks

**Comment by adityagokula2210** [comment]
Hello @rsanjuan87,
Unfortunately, i was not able to generate the issue at my end. However, can you please check by replacing

**implementation 'com.cometchat:pro-android-chat-sdk:2.0.3'**

with

**implementation ('com.cometchat:pro-android-chat-sdk:2.0.3'){
        exclude group: 'xpp3', module: 'xpp3'
    }**

This should exclude the xpp module from CometChat dependency and it should work. Please let me know if this solves the problem

Thanks

**Comment by rsanjuan87** [comment]
I tried but, nop, it doesnt works for me
waiting news and new updates

**Comment by adityagokula2210** [comment]
Hello @rsanjuan87 
Revert the previous changes suggested by me and please try adding the below lines to the app-level build.gradle file. This should get it to work:

**configurations {
  all*.exclude group: 'xpp3', module: 'xpp3'
}**

Thanks
