### ISSUE TITLE
[2.1.0] User's Last Active time is incorrect

### ISSUE THREAD

**Issue by masterofn1** [cometchat-pro/android-chat-sdk#34]
**Describe the bug**
User's Last Active time is incorrect even after updating the user last Active time

**To Reproduce**
1. Update the user status
2. Update the last active time of the said user

**Expected behavior**

 The submitted "lastActiveAt" of the certain user should be the latest one being passed on the sdk's method
[CometChat.updateUser](https://prodocs.cometchat.com/docs/android-users-user-management)

**Actual behavior**

  The response of the method requests always give incorect time.
In my case it was always in year 1970

**Enviorment/Platfrom (please complete the following information):**
 - Android API Versions: Android 10 and Android 8
 - CometChat SDK Version: 2.1.0

**Files (Optional)**
 - `build.gradle` (Project Level)
_implementation 'com.cometchat:pro-android-chat-sdk:2.1.0'_

**Logs (Error Logs)**
```
**Response Data**:
User{uid='kenadmin', name='ken admin', avatar='https://dev.lemi.travel/avatar/kenadmin?context=chat', link='null', role='default', metadata=null, status='offline', statusMessage='null', lastActiveAt=1599662517, hasBlockedMe=false, blockedByMe=false}

**Submitted Data**:
User{uid='kenadmin', name='ken admin', avatar='https://dev.lemi.travel/avatar/kenadmin?context=chat', link='null', role='default', metadata=null, status='offline', statusMessage='null', lastActiveAt=1599662518083, hasBlockedMe=false, blockedByMe=false}
```

**Comment by adityagokula2210** [comment]
Hello @masterofn1 ,
The lastActiveAt field cannot be updated via the SDKs. The lastActiveAt field is set based on the user sessions being created and destroyed based on the connection to the CometChat Web-socket server.

Hope this helps.
Thanks

**Comment by masterofn1** [comment]
> Hello @masterofn1 ,
> The lastActiveAt field cannot be updated via the SDKs. The lastActiveAt field is set based on the user sessions being created and destroyed based on the connection to the CometChat Web-socket server.
> 
> Hope this helps.
> Thanks

What will you recommend for us to capture the last active time of the user? it always pointed back to year 1970

**Comment by adityagokula2210** [comment]
@masterofn1 
The lastActiveAt field will only be set for the users who have logged in at least once into CometChat. What I would suggest is that you check if the lastActiveAt field. If it is set to 0, it means that the user has not logged in to CometChat. If the lastActiveAt field is not 0, it means it shows the timestamp of the last time the user was connected to the CometChat web-socket servers.

Thanks
