### ISSUE TITLE
[2.3.5] Calls are not working  on some countries on Android Version Only

### ISSUE THREAD

**Issue by Andro-Samurai** [cometchat-pro/android-chat-sdk#36]
**Describe the bug**
our client from Country of Oman cannot start chat from Android only, iOS is working fine
we tried multiple WIFI networks
we've tried the same app the same phones from another country and it works fine
We've tried your sample and the same issue is happening.

here is the log
[cometchat+(1).txt](https://github.com/cometchat-pro/android-chat-sdk/files/6759651/cometchat%2B.1.txt)
here is a video
https://user-images.githubusercontent.com/25287348/124379813-d5480d80-dcc1-11eb-8e11-6ce9dd567009.mp4

**Comment by proveshapyne** [comment]
Hey @Andro-Samurai,

I wanted to let you know that I am closing this ticket as we are communicating via email. We can stay connected there.

Thank you!

Regards,
Provesha
