### ISSUE TITLE
[2.3.5] Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'int java.util.Timer.purge()' on a null object reference com.cometchat.pro.core.PingController.stopPing

### ISSUE THREAD

**Issue by ecemmine** [cometchat-pro/android-chat-sdk#37]
App crashes, crash log:

com.cometchat.pro.core.PingController.stopPing (PingController.java:3)
com.cometchat.pro.core.CometChat.loginFail (CometChat.java:1)
com.cometchat.pro.core.CometChat.login (CometChat.java:139)
utils.CometChatHelper.internalLogin (CometChatHelper.java:56)
utils.CometChatHelper.access$internalLogin (CometChatHelper.java:16)
utils.CometChatHelper$internalLogin$1.onError (CometChatHelper.java:64)
com.cometchat.pro.core.CometChat$9.run (CometChat.java:1)

**Comment by adityagokula2210** [comment]
@ecemmine 
Can you please let us know when this issue is encountered. It would be really helpful if you could let us know the steps to reproduce the issue.

**Comment by ecemmine** [comment]
@adityagokula2210 I saw this crash in firebase logs. Encountered while the app was in the background

**Comment by adityagokula2210** [comment]
Hello @ecemmine 
Unfortunately,
We were not able to reproduce the crash at our end. However, we have added a few checks in the SDK and released a new version of the CometChat SDK (version 2.4.1). Please upgrade to the latest version and that will make sure that this crash is not encountered again.
