### ISSUE TITLE
[Feature] Expose websocket connection status

### ISSUE THREAD

**Issue by randspace0** [cometchat-pro/android-chat-sdk#40]
Title explains it

**Comment by proveshapyne** [comment]
Hey @andraantariksa,

Thanks for submitting this ticket. We will be happy to help.

Can you give us more information about your use case and your requirement?

**Comment by proveshapyne** [comment]
Hi @andraantariksa,

We have closed this ticket as we haven't heard back from you. Please [submit a ticket](https://help.cometchat.com/hc/en-us/requests/new) through our Help Center if you want to revisit this or if you need more help.
Thank you.

Provesha Pyne
CometChat
