### ISSUE TITLE
[1.8.3] Incorrect Text Message validation with Message Type MESSAGE_TYPE_IMAGE

### ISSUE THREAD

**Issue by yadavmangesh** [cometchat-pro/android-chat-sdk#7]
**Describe the bug**
While Sending a text message with messageType `MESSAGE_TYPE_IMAGE` it shows: A file input is required for the message type image under category message instead of showing that text message requires `MESSAGE_TYPE_TEXT` as messageType

**To Reproduce**
1. Login with UID
2. Send Text Message with  messageType `MESSAGE_TYPE_IMAGE` 

**Expected behavior**

 Exception showing text message requires `MESSAGE_TYPE_TEXT` as messageType under 
 category message 

**Actual behavior**

  A file input is required for the message type image under category message

**Enviorment/Platfrom (please complete the following information):**
 - Android API Version[ Android 7.1.1 || API-25]
 - CometChat SDK Version[1.8.3]

**Logs (Error Logs)**
- Error Log
      A file input is required for the message type image under category message
- Debug Log
     A file input is required for the message type image under category message

**Comment by adityagokula2210** [comment]
Fixed
