### ISSUE TITLE
[1.8.3] Parameter validation in constructor of TextMessage, MediaMessage,CustomMessage and CallMessage

### ISSUE THREAD

**Issue by yadavmangesh** [cometchat-pro/android-chat-sdk#8]
**Describe the bug**
 Validation for the required parameter in constructors  is not working 

**To Reproduce**
Pass Different parameters than required in the constructor

**Expected behavior**
  Compile-time error or Warning for passing the Wrong Parameter in the constructor 

**Actual behavior**
Error response in `onError()` method 

**Enviorment/Platfrom (please complete the following information):**
 - Android API Version[Android 7.1.1 || API 21 ]
 - CometChat SDK Version[1.8.3]

**Logs (Error Logs)**
- Error Log
  error Message: Failed to validate the data sent with the request.
 
**Additional context**

 Constructor Created was 

       TextMessage textMessage=new TextMessage(UID,null, 
        CometChatConstants.CALL_TYPE_VIDEO,CometChatConstants.CATEGORY_MESSAGE);

**Comment by adityagokula2210** [comment]
Done
