### ISSUE TITLE
[1.8.3] MUID is null in response Message

### ISSUE THREAD

**Issue by yadavmangesh** [cometchat-pro/android-chat-sdk#9]
**Describe the bug**
While sending a text message `MUID` is been set but in `onSucess()`     `MUID `  is null in the message object

**To Reproduce**
 send a text message with and set  MUID in the message object 

**Expected behavior**
 Set value of MUID should be return in `onSucess()`  response 

**Actual behavior**
 null value of MUID in  `onSucess()`

**Enviorment/Platfrom (please complete the following information):**
 - Android API Version[Android 7.1.1 ||  API 21 ]
 - CometChat SDK Version[1.8.3]

**Logs (Error Logs)**
- No error log
 
**Additional context**
 The message gets successfully sent and the MUID field returned is null

**Comment by adityagokula2210** [comment]
Fixed
